// Simple Hancock program to print out the contents of the map generated by
// countIntl2.
// Do not run this for any large maps!!

#include "scampRec.hh"

map intlCount_m	{
  key (MINVALIDPN .. MAXVALIDPN-1);
  split	(10000,	1000);
  value	int;
  default 0;
};

void sig_main(exists intlCount_m ic <I:>) {

  iterate(over ic) {
    event (pn_t	*l) {
      sfprintf(sfstdout,"%lld ==> %d\n",*l, ic<:*l:>);
    }
  }

}
